"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Persona_1 = require("./Persona");
var Direccion_1 = require("./Direccion");
var Telefono_1 = require("./Telefono");
var Mail_1 = require("./Mail");
var persona1 = new Persona_1.Persona("Juan", "García", 30, "12345678A", 19920101, "azul", "hombre", new Direccion_1.Direccion("Calle Mayor", 1, 2, "A", 28001, "Madrid", "Madrid"), new Telefono_1.Telefono("Móvil", 666555444), new Mail_1.Mail("Personal", "juan.garcia@mail.com"), "Notas de Juan");
var persona2 = new Persona_1.Persona("María", "González", 25, "87654321B", 19961231, "rojo", "mujer", new Direccion_1.Direccion("Calle del Sol", 3, 1, "B", 41001, "Sevilla", "Sevilla"), new Telefono_1.Telefono("Casa", 955123456), new Mail_1.Mail("Trabajo", "maria.gonzalez@empresa.com"), "Notas de María");
var persona3 = new Persona_1.Persona("Pedro", "Martínez", 40, "11111111C", 19820115, "verde", "hombre", new Direccion_1.Direccion("Avenida de la Libertad", 15, 4, "C", 50001, "Zaragoza", "Zaragoza"), new Telefono_1.Telefono("Trabajo", 976654321), new Mail_1.Mail("Personal", "pedro.martinez@mail.com"), "Notas de Pedro");
console.log("Registros originales:");
console.log(persona1.obtenerDatos());
console.log(persona2.obtenerDatos());
console.log(persona3.obtenerDatos());
var nuevaDireccion = new Direccion_1.Direccion("Calle Nueva", 10, 2, "D", 50002, "Zaragoza", "Zaragoza");
var nuevoTelefono = new Telefono_1.Telefono("Móvil", 666444222);
var nuevoMail = new Mail_1.Mail("Trabajo", "pedro.martinez@empresa.com");
persona3.modificarRegistro(nuevaDireccion, nuevoTelefono, nuevoMail);
console.log("Registros actualizados:");
console.log(persona1.obtenerDatos());
console.log(persona2.obtenerDatos());
console.log(persona3.obtenerDatos());
